# Generated by Django 3.2 on 2021-06-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_borrow_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
