# Generated by Django 3.2 on 2021-06-03 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_borrow_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='customer',
        ),
        migrations.AddField(
            model_name='borrow',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
